ko_fi: felipewove
custom: ['https://app.picpay.com/user/felipebrigatto', 'https://recargapay.com.br/r/8YqbZak', 'https://www.mercadopago.com.br/checkout/v1/redirect?pref_id=77089538-1441541d-a291-4b51-b997-d0c86f354690']
